<?
	include_once 'users.php';
?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Table with users</title>
	<link rel="stylesheet" type="text/css" href="css/bootstrap.css">
	<link rel="stylesheet" type="text/css" href="css/main.css">
</head>
<body>
<div class="container">
<form method="post">
  <div class="form-group">
    <label for="name">Name</label>
    <input type="text" class="form-control" id="name" name="user-name" placeholder="Name">
  </div>
  <div class="form-group">
    <label for="second_name">Second Name</label>
    <input type="text" class="form-control" id="second-name" name="user-second_name" placeholder="Second Name">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" name="user-mail" placeholder="Enter email">
  </div>
  <a href="index.php"><button type="button" class="btn btn-default" name="back">Back to the table</button></a>
  <button type="submit" class="btn btn-default" name="add-user">Add</button>
</form>
</div>
</body>
</html>